DROP DATABASE CINEMAPARADISO;
CREATE DATABASE CINEMAPARADISO;
USE CINEMAPARADISO;

CREATE TABLE CINEPHILES(
	EMAIL NVARCHAR(255) PRIMARY KEY,
	PASSWORDHASH TEXT,
	CINENAME NVARCHAR(50),
	CINELASTNAME NVARCHAR(50),
	AGE INT,
	CINEIMAGE NVARCHAR (50)
);

INSERT INTO CINEPHILES VALUES ('andres.san.ro@outlook.com', 'andressanro', 'Andres', 'Sanchez Robleno', 23, 'andres.png');

CREATE TABLE MOVIES(
	IDMOVIE INT IDENTITY(1,1) PRIMARY KEY,
	TITLE NVARCHAR(50),
	GENRE NVARCHAR(255),
	DIRECTOR NVARCHAR(100),
	PRODUCTOR NVARCHAR(100),
	ACTOR NVARCHAR(255),
	SYNOPSIS TEXT,
	MOVIEIMAGE NVARCHAR(50),
	METAPUNTUATION DECIMAL(1,1)
);

INSERT INTO MOVIES VALUES('La jungla de cristal', 'Accion;Blockbuster', 'John McTiernan', NULL, 'Bruce Willis', NULL, 'movie.png', 0);
--select * from MOVIES;

CREATE TABLE LISTS(
	IDMOVIE INT,
	CINEEMAIL NVARCHAR(255),
	REVIEW TEXT,
	PUNTUATION DECIMAL(1,1)
	CONSTRAINT fk_lm FOREIGN KEY (IDMOVIE) REFERENCES MOVIES (IDMOVIE)
		ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_lC FOREIGN KEY (CINEEMAIL) REFERENCES CINEPHILES (EMAIL)
		ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY (IDMOVIE, CINEEMAIL)
);