DROP DATABASE CINEMAPARADISO;
CREATE DATABASE CINEMAPARADISO;
USE CINEMAPARADISO;

CREATE TABLE CINEPHILES(
	EMAIL NVARCHAR(255) PRIMARY KEY,
	PASSWORDHASH TEXT,
	CINENAME NVARCHAR(50),
	CINELASTNAME NVARCHAR(50),
	AGE INT,
	CINEIMAGE NVARCHAR (50)
);

INSERT INTO CINEPHILES VALUES ('andres.san.ro@outlook.com', 'andressanro', 'Andrés', 'Sánchez Robleño', 23, 'andres.png');

CREATE TABLE LISTS(
	IDMOVIE INT,
	CINEEMAIL NVARCHAR(255),
	REVIEW TEXT,
	PUNTUATION DECIMAL(1,1)
	CONSTRAINT fk_lm FOREIGN KEY (IDMOVIE) REFERENCES MOVIES (IDMOVIE)
		ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_lC FOREIGN KEY (CINEEMAIL) REFERENCES CINEPHILES (EMAIL)
		ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY (IDMOVIE, CINEEMAIL)
);